In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split

In [7]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [8]:
iris.data.shape

(150, 4)

In [15]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [40]:
x = [[5.1, 3.5, 1.4],
 [4.9, 3.,  1.4],
 [4.7, 3.2, 1.3],
 [4.6, 3.1, 1.5],
 [5.,  3.6, 1.4],
 [5.4, 3.9, 1.7],
 [4.6, 3.4, 1.4]]
print(np.shape(x))

(7, 3)


In [36]:
x, y = iris.data[:,:-1], iris.data[:,-1]
print(x)

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]
 [5.4 3.9 1.7]
 [4.6 3.4 1.4]
 [5.  3.4 1.5]
 [4.4 2.9 1.4]
 [4.9 3.1 1.5]
 [5.4 3.7 1.5]
 [4.8 3.4 1.6]
 [4.8 3.  1.4]
 [4.3 3.  1.1]
 [5.8 4.  1.2]
 [5.7 4.4 1.5]
 [5.4 3.9 1.3]
 [5.1 3.5 1.4]
 [5.7 3.8 1.7]
 [5.1 3.8 1.5]
 [5.4 3.4 1.7]
 [5.1 3.7 1.5]
 [4.6 3.6 1. ]
 [5.1 3.3 1.7]
 [4.8 3.4 1.9]
 [5.  3.  1.6]
 [5.  3.4 1.6]
 [5.2 3.5 1.5]
 [5.2 3.4 1.4]
 [4.7 3.2 1.6]
 [4.8 3.1 1.6]
 [5.4 3.4 1.5]
 [5.2 4.1 1.5]
 [5.5 4.2 1.4]
 [4.9 3.1 1.5]
 [5.  3.2 1.2]
 [5.5 3.5 1.3]
 [4.9 3.6 1.4]
 [4.4 3.  1.3]
 [5.1 3.4 1.5]
 [5.  3.5 1.3]
 [4.5 2.3 1.3]
 [4.4 3.2 1.3]
 [5.  3.5 1.6]
 [5.1 3.8 1.9]
 [4.8 3.  1.4]
 [5.1 3.8 1.6]
 [4.6 3.2 1.4]
 [5.3 3.7 1.5]
 [5.  3.3 1.4]
 [7.  3.2 4.7]
 [6.4 3.2 4.5]
 [6.9 3.1 4.9]
 [5.5 2.3 4. ]
 [6.5 2.8 4.6]
 [5.7 2.8 4.5]
 [6.3 3.3 4.7]
 [4.9 2.4 3.3]
 [6.6 2.9 4.6]
 [5.2 2.7 3.9]
 [5.  2.  3.5]
 [5.9 3.  4.2]
 [6.  2.2 4. ]
 [6.1 2.9 4.7]
 [5.6 2.9 3.6]
 [6.7 3.1 4.4]
 [5.6 3.  

###  Gini impurity

Decision trees use the concept of Gini impurity to describe how “pure” a node is. A node is pure (G = 0) if all its samples belong to the same class, while a node with many samples from many different classes will have a Gini closer to 1.

$G = 1 - \sum_{k=1}^{n}p_{k}^2$

For example if a node contains five samples, with two belonging to the first class (first flower), two of class 2, one of class 3 and none of class 4, then

$G = 1 - (\frac{2}{5})^2 - (\frac{2}{5})^2 - (\frac{1}{5})^2 = 0.64$

In [19]:
class A:
    
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.info_gain = info_gain

        self.value = value

In [45]:
class DecisionTreeClassifier():
    def __init__(self, min_features_split=2, max_depth=2): 
        self.root = None
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
    def buid_tree(self, data, depth=0):
        x = data[:,:-1]
        y = data[:,-1]
        features, characters = np.shape(x)
        if features >= self.min_features_split and depth <= max_depth:
            Split = split(features, characters, data)
            l_tree = self.build_tree(Split["left_value"], depth + 1)
            r_tree = self.build_tree(Split["right_value"], depth + 1)
            return Node(Split["character"], Split["division"], l_tree, r_tree, Split["info_gain"])
        leafs_value = self.calculate_leaf_value(y)
        return Node()
        

    def split(self, features, characters, data):
        Split = {}
        max_info_gain = -math.inf
        for character in range(characters):
            char_val = data[:, character]
            posible_division = np.unique(char_val)
            for division in posible_division:
                left_side = []
                right_side = []
                for i in data:
                    if i[character] > test_division:
                        right_side = np.array(i)
                for i in data:
                    if i[character] <= test_division:
                        left_side = np.array(i)
                if len(left_side) != 0 and len(right_side) != 0:
                    value, left_value, right_value = data[:, -1], left_side[:, -1], right_side[:, -1]
                    info_gain = self.inform_gain(value, left_value, right_value)
                    if info_gain > max_info_gain:
                        Split["character"] = character
                        Split["division"] = division
                        Split["left_value"] = left_value
                        Split["right_value"] = right_value
                        Split["info_gain"] = info_gain
                        max_info_gain = info_gain
        return Split
    
    def inform_gain(self, value, left_value, right_value):
        left = len(left_value) / len(value)
        right = len(right_value) / len(value)
        return self.gini(value) - (left * self.gini(left_value) + right * self.gini(right_value))
        
    def gini(self, value):
        GINI = 0
        VALUE = np.unique(value)
        for i in VALUE:
            v = len(VALUE[VALUE == cls]) / len(VALUE)
            GINI += v**2
        return 1 - GINI
    
    def fit(self, X, Y):
        return self.root = self.buid_tree(np.concatenate((X, Y), axis=1))

    def predict(self, X):
        return np.array(list(map(lambda x: self.make_prediction(x, self.root), X)))
    
    def make_prediction(self, x, tree):
        if tree.value!=None: 
            return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)
    